# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "deploy"
  

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "cgdevopsgcp/tomcat"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  DeployingApps:
    type: freestyle
    stage: 'deploy'
    steps:
      DeployApp1:
        title: Deploying App 1
        stage: deploy
        image: gcr.io/my-project-56312-343412/nginx@sha256:2468d48e476b6a079eb646e87620f96ce1818ac0c5b3a8450532cea64b3421f4
        working_directory: ./my-nestjs-project/
        commands: 
          - kubectl apply -f deployment.yml service.yml

